spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: false
  flyway:
    enabled: true
    baseline-version: 1.0.0
server:
  port: 30000
  http2:
    enabled: true
management:
  health:
    ldap:
      enabled: false
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ldapsync?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      indent_output: true